---
# Go should be installed before nvim cause vim-go requires go get command
- name: Install
  include_tasks: "{{ item }}"
  loop:
    - shell.yml
    - go.yml
    - vim.yml
    - nvim.yml
    - git.yml
