---
- name: Install neovim (nvim)
  become: yes
  community.general.zypper:
    name:
      - neovim
      - python3-neovim
    state: present

- name: Ensure ~/.config/nvim/autoload exists
  become_user: "{{ env_user }}"
  file:
    path: "~/.config/nvim/autoload"
    state: directory

- name: Install vim-plug
  become_user: "{{ env_user }}"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.config/nvim/autoload/plug.vim"
    force: yes

- name: Copy nvim config directory
  become_user: "{{ env_user }}"
  ansible.builtin.copy:
    src: "nvim/"
    dest: "~/.config/nvim/"

- name: Installing plugins by vim-plug using PlugInstall command
  shell: "nvim -u $HOME/.config/nvim/init-plug.vim -c PlugInstall -c qa"
