---
- name: Install vim
  become: yes
  community.general.zypper:
    name: vim
    state: present

- name: Copy vimrc
  become_user: "{{ env_user }}"
  ansible.builtin.copy:
    src: "vim/.vimrc"
    dest: "~/.vimrc"
