---
all:
  hosts:
    test-archlinux-vagrant:
      ansible_port: 2222
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/vagrant-boxes/archlinux/.vagrant/machines/default/virtualbox/private_key
      env_has_x11: yes
      env_user: john
    test-ubuntu-1804-vagrant:
      ansible_port: 2200
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/vagrant-boxes/ubuntu-1804/.vagrant/machines/default/virtualbox/private_key
      env_has_x11: no
      env_user: john
