---
apps_arch:
  - git
  - vim
  - neovim
  - python-pynvim  # Neovim Python support
  - tmux
  - base-devel
  - python2
  - python2-virtualenv
  - python
  - python-virtualenv
  - jedi-language-server
  - ipython
  - colordiff
  - ripgrep  # Only available in Arch as a package. Manual installatino on other distros is required
  - diff-so-fancy  # Only available in Arch as a package. Manual installatino on other distros is required
  - entr
  - cppcheck
  - gdb
  - valgrind
  - doxygen
  - eslint
  - go
  - go-tools
  - xsel  # tmux-yank requires this
