---
- name: Upgrade the system
  pacman:
    upgrade: yes

- name: Install applications for Archlinux
  pacman:
    name: "{{ apps_arch }}"

- name: Ensure .bashrc.d exists
  become_user: "{{ env_user }}"
  file:
    path: "~/.bashrc.d"
    state: directory
