---
- name: Install keychain
  pacman:
    name: keychain

- name: Enable keychain
  become_user: "{{ env_user }}"
  copy:
    dest: "~/.bashrc.d/keychain.bash"
    content: |
      eval $(keychain --eval --quiet id_rsa)
