---

- name: Ensure ~/.local/bin/ eixsts
  become_user: "{{ env_user }}"
  file:
    path: "$HOME/.local/bin"
    state: directory

- name: Install bd
  become_user: "{{ env_user }}"
  get_url:
    url: https://raw.githubusercontent.com/vigneshwaranr/bd/master/bd
    dest: "$HOME/.local/bin/bd"
    mode: 0755
    force: yes
