---
- name: Pull latest pyenv from GitHub
  become_user: "{{ env_user }}"
  git:
    dest: "~/.pyenv"
    repo: https://github.com/pyenv/pyenv.git
    depth: 1

- name: Install pyenv prerequisites for Arch
  pacman:
    name:
      - base-devel
      - openssl
      - zlib
      - bzip2
      - readline
      - sqlite
      - wget
      - curl
      - llvm
      - xz
      - tk
      - libffi
