---
- name: Check if pyenv was installed not via pacman
  # In an older version of this playbook, pyenv was installed via git,
  # not pacman.
  become_user: "{{ env_user }}"
  shell: "ls ~/.pyenv/ && ! pacman -Qs pyenv"
  register: pyenv_not_via_pacman
  ignore_errors: yes

- name: Remove pyenv which is not installed by pacman
  become_user: "{{ env_user }}"
  when: pyenv_not_via_pacman is succeeded
  file:
    path: "~/.pyenv/"
    state: absent

- name: Install pyenv and build dependencies
  pacman:
    name:
      - pyenv
      - base-devel
      - openssl
      - zlib
      - xz

- name: Enable pyenv
  become_user: "{{ env_user }}"
  copy:
    dest: "~/.bashrc.d/pyenv.bash"
    content: |
      if command -v pyenv 1>/dev/null 2>&1; then
          eval "$(pyenv init -)"
      fi
