---
- name: Check if fzf was installed not via pacman
  # In an older version of this playbook, pyenv was installed via git,
  # not pacman.
  become_user: "{{ env_user }}"
  shell: "ls ~/.fzf/"
  register: fzf_not_via_pacman
  ignore_errors: yes

- name: Remove fzf which is not installed by pacman
  become_user: "{{ env_user }}"
  when: fzf_not_via_pacman is succeeded
  file:
    path: "~/.fzf/"
    state: absent

- name: Install fzf
  pacman:
    name: fzf

- name: Enable fzf
  become_user: "{{ env_user }}"
  copy:
    dest: "~/.bashrc.d/fzf.bash"
    content: |
      source /usr/share/fzf/key-bindings.bash
      source /usr/share/fzf/completion.bash
