---
- name: Installing bash-git-prompt
  become_user: "{{ env_user }}"
  git:
    dest: "~/.bash-git-prompt"
    repo: https://github.com/magicmonty/bash-git-prompt.git
    depth: 1

- name: Enable bash-git-prompt
  become_user: "{{ env_user }}"
  copy:
    dest: "~/.bashrc.d/bash-git-prompt.bash"
    content: |
      export GIT_PROMPT_ONLY_IN_REPO=1
      export GIT_PROMPT_SHOW_UNTRACKED_FILES=normal
      [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ] && source "$HOME/.bash-git-prompt/gitprompt.sh"
