---
- name: Installing applications for Archlinux
  include_tasks: archlinux.yml

- name: Installing docker
  include_tasks: install_docker.yml

- name: Installing fzf
  include_tasks: install_fzf.yml

- name: Installing bash-git-prompt
  include_tasks: install_bash-git-prompt.yml

- name: Installing keychain
  include_tasks: install_keychain.yml

- name: Installing pyenv
  include_tasks: install_pyenv.yml

- name: Installing bd
  include_tasks: install_bd.yml
