---
- name: Copy nvim config directory
  shell: "cp -rf {{ dotfiles_repo_path }}/nvim/HOME/.config $HOME/" 

- name: Installing plugins by vim-plug using PlugInstall command
  shell: "nvim -u $HOME/.config/nvim/init-plug.vim -c PlugInstall -c qa"
