---
- debug:
    msg: "Install Python {{ python_version }} through pyenv"

- name: Copy the pyenvrc file
  copy:
    src: pyenvrc.sh
    dest: /tmp/pyenvrc.sh

- name: Install specified Python version
  shell: ". /tmp/pyenvrc.sh; pyenv install -s {{ python_version }}"

- name: Upgrade pip for the installed Python
  environment:
    PYENV_VERSION: "{{python_version}}"
  shell: ". /tmp/pyenvrc.sh; pip install --upgrade pip"

- name: Install development environment for the installed Python
  environment:
    PYENV_VERSION: "{{python_version}}"
  shell: ". /tmp/pyenvrc.sh; pip install {{ package }}"
  loop:
    - ipython
    - flake8
    - virtualenv
    - pipenv
    - requests
    - flask
  loop_control:
    loop_var: package

- name: Clean up
  file:
    state: absent
    path: /tmp/pyenvrc.sh
