---
- name: Ensure the directory for TPM exists
  file:
    path: "$HOME/.tmux/plugins"
    state: directory
  become: yes
  become_user: "{{ deploy_user }}"

- name: Install TPM
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "$HOME/.tmux/plugins/tpm"
  become: yes
  become_user: "{{ deploy_user }}"

- name: Copy tmux config file
  shell: "cp {{ dotfiles_repo_path }}/tmux/HOME/.tmux.conf $HOME/"
  become: yes
  become_user: "{{ deploy_user }}"

- name: Adjust plugin tmux-yank copy command for system without X11
  when: not has_x11
  lineinfile:
    path: "$HOME/.tmux.conf"
    line: "set -g @override_copy_command 'tee > /dev/null'"
    insertafter: ".*tmux-yank.*"
    state: present
  become: yes
  become_user: "{{ deploy_user }}"

- name: Adjust plugin tmux-yank copy command for system with X11
  when: has_x11
  lineinfile:
    path: "$HOME/.tmux.conf"
    line: "set -g @override_copy_command 'tee > /dev/null'"
    state: absent
  become: yes
  become_user: "{{ deploy_user }}"

- name: Install TPM plugins
  shell: "$HOME/.tmux/plugins/tpm/bin/install_plugins"
  become: yes
  become_user: "{{ deploy_user }}"
